-- SQLite

-- TABLES CREATION:



-- create table Dept(
-- ID NUMERIC(7) NOT NULL,
-- NAME VARCHAR(25)  NOT NULL,
-- CONSTRAINT DeptID_PK PRIMARY KEY (ID)
-- );

-- Create table Emp(
-- ID NUMERIC(7) NOT NULL,
-- LAST_NAME VARCHAR(25) NOT NULL,
-- FIRST_NAME VARCHAR(25) NOT NULL,
-- DEPT_ID NUMERIC(7) NOT NULL,
-- CONSTRAINT EmpID_Pk PRIMARY KEY (ID),
-- CONSTRAINT EMP_Dept_FJ FOREIGN KEY (Dept_ID) REFERENCES Dept(ID)
-- );



--QUERIES-CONSULTAS
